services:
  - type: web
    name: autolearn-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn autolearn.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: autolearn-db
          property: connectionString

databases:
  - name: autolearn-db
